changes to mount NFS to k8s service cluster - addressed review comments

diff --git a/discovery/roles/postscripts/common/templates/omnia_k8s_service_cluster_postboot.j2 b/discovery/roles/postscripts/common/templates/omnia_k8s_service_cluster_postboot.j2
--- a/discovery/roles/postscripts/common/templates/omnia_k8s_service_cluster_postboot.j2
+++ b/discovery/roles/postscripts/common/templates/omnia_k8s_service_cluster_postboot.j2
@@ -28,38 +28,6 @@ echo "$(date) - INFO - Starting Omnia Service node postboot configuration" >> "$
 
 
 {% if omnia_share_option == "NFS" %}
-# Create omnia_path directory if it does not exist
-echo "Creating omnia shared path directory if it does not exist" >> "$LOGFILE"
-mkdir -p {{ oim_shared_path }}
-
-# Validate if NFS server is reachable
-echo "Validating if NFS server is reachable" >> "$LOGFILE"
-ping -c1 -W1 {{ nfs_server_ip }} > /dev/null
-if [ $? -ne 0 ]; then
-    echo -e "NFS server {{ nfs_server_ip }} is not reachable." >> "$LOGFILE"
-    exit 1
-fi
-
-# Mount NFS server share path in Omnia share path
-echo "Mounting NFS server share path in Omnia share path" >> "$LOGFILE"
-mount -t nfs -o nosuid,rw,sync,hard,intr,timeo=30 {{ nfs_server_ip }}:{{ nfs_server_share_path }} {{ oim_shared_path }}
-
-# Validate if NFS server share path is mounted
-echo "Validating if NFS server share path is mounted" >> "$LOGFILE"
-if grep -qs "{{ nfs_server_ip }}:{{ nfs_server_share_path }}" /proc/mounts; then
-    echo -e "SUCCESS: NFS server share path is mounted." >> "$LOGFILE"
-else
-    echo -e "ERROR: NFS server share path is not mounted. Provide valid NFS server details" >> "$LOGFILE"
-    exit 1
-fi
-
-# Add NFS server share to /etc/fstab to mount on startup
-echo "Adding entry in /etc/fstab for mount on startup"
-echo "{{ nfs_server_ip }}:{{ nfs_server_share_path }} {{ oim_shared_path }} nfs nosuid,rw,sync,hard,intr" >> /etc/fstab
-
-# Applying mount based on fstab entry
-run_or_fail mount -a
-
 # ports for nfs
 firewall_ports=(
   "111/udp"
@@ -107,6 +75,38 @@ if firewall-cmd --reload; then
 else
   echo "ERROR: Failed to reload firewalld." >> "$LOGFILE"
 fi
+
+# Create omnia_path directory if it does not exist
+echo "Creating omnia shared path directory if it does not exist" >> "$LOGFILE"
+mkdir -p {{ oim_shared_path }}
+
+# Validate if NFS server is reachable
+echo "Validating if NFS server is reachable" >> "$LOGFILE"
+ping -c1 -W1 {{ nfs_server_ip }} > /dev/null
+if [ $? -ne 0 ]; then
+    echo -e "NFS server {{ nfs_server_ip }} is not reachable." >> "$LOGFILE"
+    exit 1
+fi
+
+# Mount NFS server share path in Omnia share path
+echo "Mounting NFS server share path in Omnia share path" >> "$LOGFILE"
+mount -t nfs -o nosuid,rw,sync,hard,intr,timeo=30 {{ nfs_server_ip }}:{{ nfs_server_share_path }} {{ oim_shared_path }}
+
+# Validate if NFS server share path is mounted
+echo "Validating if NFS server share path is mounted" >> "$LOGFILE"
+if grep -qs "{{ nfs_server_ip }}:{{ nfs_server_share_path }}" /proc/mounts; then
+    echo -e "SUCCESS: NFS server share path is mounted." >> "$LOGFILE"
+else
+    echo -e "ERROR: NFS server share path is not mounted. Provide valid NFS server details" >> "$LOGFILE"
+    exit 1
+fi
+
+# Add NFS server share to /etc/fstab to mount on startup
+echo "Adding entry in /etc/fstab for mount on startup"
+echo "{{ nfs_server_ip }}:{{ nfs_server_share_path }} {{ oim_shared_path }} nfs nosuid,rw,sync,hard,intr" >> /etc/fstab
+
+# Applying mount based on fstab entry
+run_or_fail mount -a
 
 {% endif %}
 
